openapi: 3.0.0
info:
  title: poc-api
  version: 1.0.0
paths:
  /api/datetime:
    get:
      summary: Get current date and time
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  datetime:
                    type: string
                    format: date-time
  /api/echo:
    post:
      summary: Echo a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        "200":
          description: Message echoed back
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
